import SwiftUI
import UniformTypeIdentifiers

/// Modal sheet for picking a report type, scope, and options. Wires the
/// user's selections to `ReportGenerator.generate(...)` and surfaces the
/// resulting bytes via the system file exporter so the user can save
/// wherever they like.
struct ReportPickerView: View {
    @Environment(AppState.self) private var appState
    @Environment(\.dismiss) private var dismiss

    @State private var type: ReportType = .pedigree
    @State private var format: ReportFormat = .pdf
    @State private var paperSize: PaperSize = .a4
    @State private var profileID: String?
    @State private var pedigreeGenerations: PedigreeGenerations = .four
    @State private var pedigreeStyle: PedigreeStyle = .rectangular
    @State private var showCompleteness: Bool = true
    @State private var focusSetID: UUID?

    /// When true and `type == .familyGroupSheet`, generate one multi-page
    /// PDF covering every family in the snapshot (DESIGN.md §7.9.3).
    @State private var batchAllFamilies: Bool = false

    /// Generated bytes waiting on a save destination — drives fileExporter.
    @State private var pendingOutput: ReportGenerator.Output?
    @State private var generationError: String?

    var body: some View {
        VStack(spacing: 0) {
            header
            Divider()
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    typeSection
                    formatSection
                    perTypeOptions
                }
                .padding(20)
            }
            Divider()
            footer
        }
        .frame(minWidth: 540, minHeight: 520)
        .onAppear {
            if profileID == nil {
                profileID = appState.currentProject?.homePersonID
                    ?? appState.snapshot.profiles.values.first?.id
            }
            if focusSetID == nil {
                focusSetID = appState.activeFocusSetID
            }
        }
        .onChange(of: type) { _, newType in
            if !newType.supportedFormats.contains(format) {
                format = newType.supportedFormats.first ?? .pdf
            }
        }
        .fileExporter(
            isPresented: Binding(
                get: { pendingOutput != nil },
                set: { if !$0 { pendingOutput = nil } }
            ),
            document: pendingOutput.map { ReportFileDocument(output: $0) },
            contentType: pendingOutput?.format == .markdown
                ? .plainText
                : .pdf,
            defaultFilename: pendingOutput?.suggestedFilename
        ) { result in
            if case .failure(let err) = result {
                generationError = "Failed to save: \(err.localizedDescription)"
            }
            pendingOutput = nil
            dismiss()
        }
        .alert("Report failed", isPresented: Binding(
            get: { generationError != nil },
            set: { if !$0 { generationError = nil } }
        )) {
            Button("OK") { generationError = nil }
        } message: {
            Text(generationError ?? "")
        }
    }

    // MARK: - Sections

    private var header: some View {
        HStack {
            Text("Generate report")
                .font(.title2).fontWeight(.semibold)
            Spacer()
        }
        .padding(20)
    }

    private var typeSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            sectionTitle("Report type")
            Picker("Type", selection: $type) {
                ForEach(ReportType.allCases) { t in
                    Label(t.displayName, systemImage: t.systemImage).tag(t)
                }
            }
            .pickerStyle(.menu)
            .labelsHidden()
            Text(type.description)
                .font(AppTypography.cardMeta)
                .foregroundStyle(.secondary)
        }
    }

    private var formatSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            sectionTitle("Format")
            Picker("Format", selection: $format) {
                ForEach(type.supportedFormats) { f in
                    Text(f.displayName).tag(f)
                }
            }
            .pickerStyle(.segmented)
            .labelsHidden()
            if format == .pdf {
                Picker("Paper", selection: $paperSize) {
                    ForEach(PaperSize.allCases) { p in
                        Text(p.displayName).tag(p)
                    }
                }
                .pickerStyle(.segmented)
            }
        }
    }

    @ViewBuilder
    private var perTypeOptions: some View {
        switch type {
        case .pedigree:
            VStack(alignment: .leading, spacing: 8) {
                sectionTitle("Subject")
                ProfilePickerField(label: "Subject", snapshot: appState.snapshot, selectedID: $profileID)
                sectionTitle("Style")
                Picker("Style", selection: $pedigreeStyle) {
                    ForEach(PedigreeStyle.allCases) { s in
                        Text(s.displayName).tag(s)
                    }
                }
                .pickerStyle(.segmented)
                .labelsHidden()
                sectionTitle("Generations")
                Picker("Generations", selection: $pedigreeGenerations) {
                    ForEach(PedigreeGenerations.allCases, id: \.self) { g in
                        Text(g.displayName).tag(g)
                    }
                }
                .pickerStyle(.segmented)
                .labelsHidden()
                Toggle("Show completeness indicators", isOn: $showCompleteness)
            }
        case .familyGroupSheet:
            VStack(alignment: .leading, spacing: 8) {
                Toggle("Export all families (one PDF)", isOn: $batchAllFamilies)
                if !batchAllFamilies {
                    sectionTitle("Subject (any family member)")
                    ProfilePickerField(label: "Subject", snapshot: appState.snapshot, selectedID: $profileID)
                } else {
                    Text("Generates one multi-page PDF with every family in the tree.")
                        .font(AppTypography.cardMeta)
                        .foregroundStyle(.secondary)
                }
            }
        case .narrative:
            VStack(alignment: .leading, spacing: 8) {
                sectionTitle("Subject")
                ProfilePickerField(label: "Subject", snapshot: appState.snapshot, selectedID: $profileID)
            }
        case .research:
            VStack(alignment: .leading, spacing: 8) {
                sectionTitle("Scope")
                if appState.focusSets.isEmpty {
                    Text("No focus sets — report will summarise the whole tree.")
                        .font(AppTypography.cardMeta)
                        .foregroundStyle(.tertiary)
                } else {
                    Picker("Focus set", selection: Binding(
                        get: { focusSetID ?? UUID() },
                        set: { focusSetID = $0 }
                    )) {
                        Text("Whole tree").tag(UUID())
                        ForEach(appState.focusSets) { f in
                            Text(f.displayTitle).tag(f.id)
                        }
                    }
                }
            }
        }
    }

    private var footer: some View {
        HStack {
            Spacer()
            Button("Cancel") { dismiss() }
                .buttonStyle(.glass)
                .keyboardShortcut(.cancelAction)
            Button("Generate") { generate() }
                .buttonStyle(.glassProminent)
                .keyboardShortcut(.defaultAction)
                .disabled(!canGenerate)
        }
        .padding(16)
    }

    // MARK: - Helpers

    private var canGenerate: Bool {
        switch type {
        case .pedigree, .narrative:
            return profileID.flatMap { appState.snapshot.profiles[$0] } != nil
        case .familyGroupSheet:
            if batchAllFamilies {
                return !appState.snapshot.profiles.isEmpty
            }
            return profileID.flatMap { appState.snapshot.profiles[$0] } != nil
        case .research:
            return true
        }
    }

    private func sectionTitle(_ text: String) -> some View {
        Text(text)
            .font(AppTypography.cardMeta.weight(.semibold))
            .foregroundStyle(.secondary)
            .textCase(.uppercase)
    }

    private func generate() {
        var options = ReportOptions(
            type: type,
            format: format,
            paperSize: paperSize,
            profileID: profileID,
            pedigreeGenerations: pedigreeGenerations,
            pedigreeStyle: pedigreeStyle,
            showCompleteness: showCompleteness,
            familyID: nil,
            focusSetID: focusSetID
        )
        if type == .familyGroupSheet {
            options.batchAllFamilies = batchAllFamilies
        }
        do {
            let output = try ReportGenerator.generate(
                options: options,
                snapshot: appState.snapshot,
                notes: appState.notes,
                questions: appState.questions,
                hypotheses: appState.hypotheses,
                focusSets: appState.focusSets,
                sessions: []
            )
            pendingOutput = output
        } catch {
            generationError = error.localizedDescription
        }
    }
}

/// Wraps generated bytes as a `FileDocument` for `.fileExporter`. Read
/// initialisation is unsupported — these documents are output-only.
private struct ReportFileDocument: FileDocument {
    static var readableContentTypes: [UTType] { [.pdf, .plainText] }
    static var writableContentTypes: [UTType] { [.pdf, .plainText] }

    let output: ReportGenerator.Output

    init(output: ReportGenerator.Output) {
        self.output = output
    }

    init(configuration: ReadConfiguration) throws {
        throw CocoaError(.featureUnsupported)
    }

    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
        FileWrapper(regularFileWithContents: output.data)
    }
}
